Depmap script update
indralab/depmap_analysis pull request #48
Opened 2020-12-15 01:21 UTC by kkaris

This PR makes some substantial changes and updates, mostly to handle analysis of drug-drug correlations in the depmap script.

Notable updates in this PR:
- Add function to produce a PyBel Signed Graph from a statement dump
- Substantially improve the Explainer class
- Use WrapException in the main script
- Migrate all explanation functions file from `depmap_analysis/scripts/depmap_script2.py` to the new file `depmap_analysis/scripts/depmap_script_expl_funcs.py`
- Move several functions from `indra_depmap_service/util.py` to `depmap_analysis/util/io_functions.py`
- Expand the `file_opener` to load objects from s3 if the path provided is a valid S3 path
- This is the first PR where typing is introduced. The idea is to introduce it to all new code from here and all code that us touched 
for each commit.
- Various docstring updates bringing the documentation more up to date

This PR is rebased on top of #46.

2020-12-16 18:13 UTC, johnbachman commented on depmap_analysis/network_functions/depmap_network_functions.py
> +def iter_chunker(n: int, iterable: Iterable):
Make consistent by using the batch_iter in indra.util.__init__; can also refactor that instance if this implementation is better

2020-12-16 18:48 UTC, johnbachman commented on depmap_analysis/resources/mito_joined.csv
> +HGNC ID,Approved symbol,Approved name,Status,Locus type,Previous symbols,Synonyms,Chromosome,NCBI Gene ID,Ensembl gene ID,Vega gene ID,Group ID,Group name,gene,count,mito_function,notes
Instead of this file, use MitoCarta 3.0 (available at https://www.broadinstitute.org/mitocarta/mitocarta30-inventory-mammalian-mitochondrial-proteins-and-pathways), pull out the gene list, and then add "mitocarta mitochondrial gene" as a type of explanation, instead of the generic "explained set"

2020-12-16 18:49 UTC, johnbachman commented on depmap_analysis/scripts/depmap_preprocessing.py
> +def get_drug_corr_matrix(drug_resp_file, drug_info_file):
Check for redundancy with depmap_analysis/network_functions/depmap_network_functions.py

2020-12-16 18:59 UTC, johnbachman requested changes
Can resolve the mitochondrial file and explanation handling in later PR; for now just implement the minor API and doc changes. 👍

2020-12-16 18:59 UTC, johnbachman commented on depmap_analysis/scripts/depmap_script_expl_funcs.py
> +"""Explainer and helper functions for depmap_script2.py When adding new
Some short docstrings describing the various functions would be helpful

2020-12-16 18:59 UTC, johnbachman commented on depmap_analysis/util/io_functions.py
> +def allowed_types(types: Iterable):
Add a comment saying that this is relevant to argument parsing

2020-12-16 22:31 UTC, kkaris commented on depmap_analysis/scripts/depmap_preprocessing.py
> +def get_drug_corr_matrix(drug_resp_file, drug_info_file):
Resolved in https://github.com/indralab/depmap_analysis/pull/48/commits/c48735c3b3fe2d243a836477834ae98c9aa136df

2020-12-17 18:55 UTC, kkaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finish up PR suggestions](https://trello.com/c/YG95h2aX/168-finish-up-pr-suggestions)

2020-12-17 18:55 UTC, kkaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finish up PR suggestions](https://trello.com/c/YG95h2aX/168-finish-up-pr-suggestions)

2020-12-17 20:17 UTC, kkaris commented on depmap_analysis/scripts/depmap_script_expl_funcs.py
> +"""Explainer and helper functions for depmap_script2.py When adding new
Fixed in https://github.com/indralab/depmap_analysis/pull/48/commits/0a8757aee871c7eeedc6dee78aa71a3dce8d6fdd

2020-12-17 20:18 UTC, kkaris commented on depmap_analysis/resources/mito_joined.csv
> +HGNC ID,Approved symbol,Approved name,Status,Locus type,Previous symbols,Synonyms,Chromosome,NCBI Gene ID,Ensembl gene ID,Vega gene ID,Group ID,Group name,gene,count,mito_function,notes
Will fix in future PR

2020-12-17 20:42 UTC, kkaris commented on depmap_analysis/util/io_functions.py
> +def allowed_types(types: Iterable):
Resolved in https://github.com/indralab/depmap_analysis/pull/48/commits/606f4bd818c138fb5854076f86a564ebef489a31

2020-12-17 21:48 UTC, kkaris commented on depmap_analysis/network_functions/depmap_network_functions.py
> +def iter_chunker(n: int, iterable: Iterable):
Working on implementing my solution to the indra version, it is ~5x faster

2020-12-18 15:16 UTC, kkaris commented on depmap_analysis/network_functions/depmap_network_functions.py
> +def iter_chunker(n: int, iterable: Iterable):
Reverted to using indra's `batch_iter` in the end. My implementation was only faster for my specific use case and it was tricky to incorporate the same functionalities in my method.

2020-12-18 15:19 UTC, kkaris commented
Finished all the updates for _this_ PR. I'll do the mitochondrial updates in another PR, same with renaming the columns in the `jaccard_df` as that is on a branch specific to the post-analysis of the drug-drug correlations

2020-12-19 00:24 UTC, johnbachman approved these changes
Looks good, feel free to merge!

2020-12-23 14:27 UTC, merged